### ISSUE TITLE
Problem with Reproducing Marco's results with Starfish

### ISSUE THREAD

**Issue by huangkun1984** [spacetx/starfish#124]
Hi. I am having difficulty passing this step in the notebook (Reproducing Marco's results with Starfish):

 

>>> s.read('ISS/fov_001/org.json')

 

 

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/usr/lib/python2.7/site-packages/starfish/io.py", line 48, in read

    self._read_stack()

  File "/usr/lib/python2.7/site-packages/starfish/io.py", line 77, in _read_stack

    im = self.read_fn(os.path.join(self.path, fname))

  File "/usr/lib64/python2.7/site-packages/numpy/lib/npyio.py", line 431, in load

    "Failed to interpret file %s as a pickle" % repr(file))

IOError: Failed to interpret file u'/newdata/data2/homes/joshr/ISS/fov_001/1_1st_Cy3 5.TIF' as a pickle

**Comment by ttung** [comment]
Can you upgrade the starfish package (`pip install --upgrade starfish`) and try again?

**Comment by huangkun1984** [comment]
Thanks! We get around that step after upgrade.

**Comment by dganguli** [comment]
awesome!
