### ISSUE TITLE
`fov.get_image('primary')` from a ragged experiment results in sadness

### ISSUE THREAD

**Issue by njmei** [spacetx/starfish#1478]
#### Description
Starfish Imagestack errors when trying to load images from a ragged experiment.

Likely relevant info: For the `primary` images we have 12 rounds where 11 of the 12 rounds have 3 'primary' channels (0, 1, 2), but round 12 only has 1 'primary' channel (0).

Probably has something to do with the [`ImageStack.from_tile_collection_data` method ](https://github.com/spacetx/starfish/blob/master/starfish/core/imagestack/imagestack.py#L98) assuming that `axes_sizes` are scalars.

#### Steps/Code to Reproduce

[problematic_starfish_metadata.zip](https://github.com/spacetx/starfish/files/3453706/problematic_starfish_metadata.zip)

```
from starfish import Experiment

exp = Experiment.from_json('see_attached_experiment_json_above.json')

for fov_name, fov in exp.items():
    primary = fov.get_image('primary')
```

#### Expected Results
No error is thrown when trying to `get_image('primary')` from an `fov` instance.

#### Actual Results
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/imaging/anaconda2/envs/mfish_pipeline/lib/python3.7/site-packages/starfish/core/experiment/experiment.py", line 156, in get_image
    return next(stack_iterator)
  File "/home/imaging/anaconda2/envs/mfish_pipeline/lib/python3.7/site-packages/starfish/core/experiment/experiment.py", line 218, in __next__
    stack = ImageStack.from_tileset(self.tileset, aligned_group)
  File "/home/imaging/anaconda2/envs/mfish_pipeline/lib/python3.7/site-packages/starfish/core/imagestack/imagestack.py", line 259, in from_tileset
    return ImageStack.from_tile_collection_data(tile_data)
  File "/home/imaging/anaconda2/envs/mfish_pipeline/lib/python3.7/site-packages/starfish/core/imagestack/imagestack.py", line 159, in from_tile_collection_data
    r=selector[Axes.ROUND], ch=selector[Axes.CH], z=selector[Axes.ZPLANE])
  File "/home/imaging/anaconda2/envs/mfish_pipeline/lib/python3.7/site-packages/starfish/core/imagestack/parser/crop.py", line 299, in get_tile
    self.backing_tile_collection_data.get_tile(r, ch, z),
  File "/home/imaging/anaconda2/envs/mfish_pipeline/lib/python3.7/site-packages/starfish/core/imagestack/parser/tileset/_parser.py", line 123, in get_tile
    self.tiles[TileKey(round=r, ch=ch, zplane=z)],
KeyError: (round: 12 ch: 1 z: 0)
```

#### Versions
Linux-4.4.0-157-generic-x86_64-with-debian-stretch-sid
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
NumPy 1.17.0
SciPy 1.3.0
scikit-image 0.15.0
pandas 0.25.0
sklearn 0.21.2
xarray 0.12.3
sympy 1.4
starfish 0.1.4+12.g8047d7a

**Comment by ttung** [comment]
The issue is that there is a bad error message (#1438).

You have to use the slice operations to load up a regular tensor, so `get_images('primary', rounds(range(11)))`

**Comment by njmei** [comment]
What to do with that dangling single channel 12th round?

**Comment by shanaxel42** [comment]
opened #1483 to deal with this use case

**Comment by ttung** [comment]
@njmei  I would just load that other round as a separate ImageStack.  Please re-open and let me know if you have any concerns with that model.
