### ISSUE TITLE
TileSet code path still exists

### ISSUE THREAD

**Issue by joshmoore** [spacetx/starfish#646]
spacetx-fov-writer wasn't updated to use a manifest file:

```
{
    "version": "4.0.0",
    "auxiliary_images": { },
    "extras": { },
    "primary_images": "hybridization-fov_000.json",
```

Loading its output via:

```
from starfish.experiment.experiment import Experiment
from starfish.types import Indices
experiment = Experiment.from_json(
    "http://nginx:9000/public/fov_000/experiment.json",
    strict=True)
image = experiment.fov().primary_image
image.show_stack({Indices.CH: 0})
```

led to:

```
Traceback (most recent call last):
  File "/tmp/example.py", line 9, in <module>
    strict=True)  # soon: allow_caching=False
  File "/src/starfish/experiment/experiment.py", line 207, in from_json
    for fov_name, primary_tileset in primary_image.all_tilesets():
AttributeError: 'TileSet' object has no attribute 'all_tilesets'
```

**Comment by joshmoore** [comment]
Dupe of gh-614.
