### ISSUE TITLE
AttributeError: 'function' object has no attribute 'shape' when running get_merfish_u20s_data.py 

### ISSUE THREAD

**Issue by zperova** [spacetx/starfish#657]
I get the following error when trying to run ``` get_merfish_u20s_data.py ```

``` 
(merfish) C02X488AJHD2:starfish zina$ pythonw starfish/examples/get_merfish_u20s_data.py merfish merfish_formatted
Traceback (most recent call last):
  File "starfish/examples/get_merfish_u20s_data.py", line 136, in <module>
    format_data(args.input_dir, args.output_dir)
  File "starfish/examples/get_merfish_u20s_data.py", line 123, in format_data
    default_shape=SHAPE
  File "/anaconda3/envs/merfish/lib/python3.6/site-packages/starfish/experiment/builder/__init__.py", line 169, in write_experiment_json
    default_shape=default_shape,
  File "/anaconda3/envs/merfish/lib/python3.6/site-packages/starfish/experiment/builder/__init__.py", line 106, in build_image
    tile.numpy_array = image.tile_data
  File "/anaconda3/envs/merfish/lib/python3.6/site-packages/slicedimage/_tile.py", line 39, in numpy_array
    assert self.tile_shape == numpy_array.shape
AttributeError: 'function' object has no attribute 'shape'
```

Running through PyCharm in conda environment on High Sierra, Python 3.6.6

**Comment by ttung** [comment]
Please update your repo and let me know if you still see this problem!  Thanks!!
