### ISSUE TITLE
`504 Server Error` on starfish.data.allen_smFISH(use_test_data=True)

### ISSUE THREAD

**Issue by joshmoore** [spacetx/starfish#882]
Capturing this mostly in case it becomes more prevalent. I was running the following in order to check the sizes of each test data set:

```
import starfish.data
import os

for x in ("MERFISH", "allen_smFISH", "DARTFISH", "ISS", "osmFISH"):
    os.environ["STARFISH_CONFIG"] = '{"backend": {"cache": {"directory": "x-%s"}}}' % x
    getattr(starfish.data, x)(use_test_data=True).fov()["primary"]  # download
```

and got:

```
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:10<00:00,  1.50it/s]
 28%|███████████████████████████▌                                                                     | 29/102 [00:42<01:40,  1.38s/it]Traceback (most recent call last):
  File "loop.py", line 6, in <module>
    getattr(starfish.data, x)(use_test_data=True).fov()["primary"]  # download
  File "/scratch/repos/starfish/starfish/experiment/experiment.py", line 96, in __getitem__
    self._images[item] = ImageStack(self._images[item])
  File "/scratch/repos/starfish/starfish/imagestack/imagestack.py", line 114, in __init__
    dtype = tile.numpy_array.dtype
  File "/scratch/repos/slicedimage/slicedimage/_tile.py", line 35, in numpy_array
    result = self._numpy_array_future()
  File "/scratch/repos/slicedimage/slicedimage/io.py", line 217, in _actual_future
    with _source_fh_contextmanager as fh:
  File "/scratch/repos/slicedimage/slicedimage/backends/_http.py", line 27, in __enter__
    resp.raise_for_status()
  File "/lifesci/groups/jrs/jamoore/miniconda2/envs/sf25/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://d2nhj9g34unfro.cloudfront.net/20181005/allen_smFISH/fov_001/img_000000000_Bandpass488_029.tif
Exception ignored in: <bound method tqdm.__del__ of  28%|███████████████████████████▌                                                                     | 29/102 [01:12<01:40,  1.38s/it]>
Traceback (most recent call last):
  File "/lifesci/groups/jrs/jamoore/miniconda2/envs/sf25/lib/python3.6/site-packages/tqdm/_tqdm.py", line 889, in __del__
    self.close()
  File "/lifesci/groups/jrs/jamoore/miniconda2/envs/sf25/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1095, in close
    self._decr_instances(self)
  File "/lifesci/groups/jrs/jamoore/miniconda2/envs/sf25/lib/python3.6/site-packages/tqdm/_tqdm.py", line 454, in _decr_instances
    cls.monitor.exit()
  File "/lifesci/groups/jrs/jamoore/miniconda2/envs/sf25/lib/python3.6/site-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/lifesci/groups/jrs/jamoore/miniconda2/envs/sf25/lib/python3.6/threading.py", line 1053, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```

**Comment by joshmoore** [comment]
Appears to be repeatable.
