### ISSUE TITLE
Docs for "Core Objects" are empty

### ISSUE THREAD

**Issue by kevinyamauchi** [spacetx/starfish#989]
Currently the doc pages for the ["Core Objects"](https://spacetx-starfish.readthedocs.io/en/latest/api/core_objects/index.html) are empty (e.g., [ImageStack](https://spacetx-starfish.readthedocs.io/en/latest/api/core_objects/image_stack.html)). Perhaps it's a work in progress, but I wanted to raise it just in case.

![screen shot 2019-02-06 at 8 21 55 am](https://user-images.githubusercontent.com/1120672/52356036-5e22c800-29e8-11e9-8b4a-c72cf96c9135.png)

**Comment by joshmoore** [comment]
```
WARNING: autodoc: failed to import module 'imagestack.imagestack' from module 'starfish'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/spacetx-starfish/envs/latest/lib/python3.6/site-packages/Sphinx-1.8.1-py3.6.egg/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/spacetx-starfish/checkouts/latest/starfish/__init__.py", line 23, in <module>
    __version__ = pkg_resources.require("starfish")[0].version
  File "/home/docs/checkouts/readthedocs.org/user_builds/spacetx-starfish/envs/latest/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/docs/checkouts/readthedocs.org/user_builds/spacetx-starfish/envs/latest/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.24.1 (/home/docs/checkouts/readthedocs.org/user_builds/spacetx-starfish/envs/latest/lib/python3.6/site-packages), Requirement.parse('urllib3==1.23'), {'starfish'})
```

from https://readthedocs.org/api/v2/build/8509706.txt

**Comment by kevinyamauchi** [comment]
Good find, @joshmoore !

**Comment by joshmoore** [comment]
With gh-1002 and the various changes to master (like gh-997), this has now changed to:

```
WARNING: autodoc: failed to import class 'Experiment' from module 'starfish.experiment.experiment'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/spacetx-starfish/envs/latest/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 152, in import_module
    __import__(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/spacetx-starfish/checkouts/latest/starfish/__init__.py", line 23, in <module>
    __version__ = pkg_resources.require("starfish")[0].version
  File "/home/docs/checkouts/readthedocs.org/user_builds/spacetx-starfish/envs/latest/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/docs/checkouts/readthedocs.org/user_builds/spacetx-starfish/envs/latest/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'starfish' distribution was not found and is required by the application
```

**Comment by joshmoore** [comment]
Heh. GitHub doesn't know how to parse "plausibly fixes" and closed, but https://readthedocs.org/projects/spacetx-starfish/builds/8584645/ was indeed successfull! Cheers @ttung
